name: ChatStyleKeyboard
options:
  bundleIdPrefix: com.aahut
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    SWIFT_VERSION: "5.9"

targets:
  # -----------------------------
  # 1) 메인 앱 (호스트 앱)
  # -----------------------------
  ChatStyleKeyboard:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: App/Sources
      - path: App/Assets.xcassets
    info:
      path: App/Info.plist
      properties:
        UILaunchScreen: { }
        UIRequiresPersistentWiFi: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aahut.chatstyle
        # AltStore(개인 서명) 호환 위해 App Groups 등 엔타이틀먼트 제거
        CODE_SIGN_ENTITLEMENTS: ""
    # ✅ 앱이 키보드 확장을 "임베드"하도록 의존성에 embed: true 지정
    dependencies:
      - target: KeyboardExtension
        embed: true

  # -----------------------------
  # 2) 키보드 확장 타깃
  # -----------------------------
  KeyboardExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "15.0"
    productName: ChatStyleKeyboardExtension
    sources:
      - path: Keyboard/Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aahut.chatstyle.keyboard
        INFOPLIST_FILE: Keyboard/Info.plist
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    # 확장 타입을 "키보드 서비스"로 지정
    extension:
      type: com.apple.keyboard-service
    info:
      path: Keyboard/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.keyboard-service
          # ✅ 확장의 진입 클래스 (소스에 있는 클래스 이름과 일치)
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).KeyboardViewController
          NSExtensionAttributes:
            RequestsOpenAccess: true
